site_name: Zhongwei Yao
site_description: Zhoongwei Yao's personal website.
site_author: Zhongwei Yao
site_url: https://zhongweiyao.com

copyright: Copyright &copy; 2023 <a href="https://zhongweiyao.com">Zhongwei Yao</a>

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  

plugins:
  - include-markdown
  - search
  - charts:
      vega_theme: default
  # - typeset
  # - meta:
  #     meta_file: '**/.meta.yml'
  - blog:
      blog_dir: posts
      post_url_format: "{slug}"
      archive_toc: true
      categories_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags:
      tags_file: tags.md
  # - git-revision-date-localized:
  #     type: date
  #     enable_creation_date: true
  # - git-committers:
  #     repository: 
  #     branch: master
  # - rss:
  #     match_path: posts/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags 
  - mkdocs-video:
      is_video: True
      video_loop: True
  # - redirects:
      # redirect_maps:


theme:
  name: material
  favicon: favicon.ico
  logo: favicon.png
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    admonition:
      example: octicons/log-24
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow 
    - navigation.prune 
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top

extra:  
  # disqus: zhongwei-yao
  analytics:
    provider: google
  generator: false
  social:
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?user=9fh_cZ8AAAAJ&hl=en
    - icon: fontawesome/solid/paper-plane
      link: mailto:yaozhongwei@zufe.edu.cn

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - fenced_code
  - extra
  - md_in_html
  - mdx_math
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  # - CV: cv.pdf
  - Research: research.md
  - Blog:
      - posts/index.md
      - Tags: tags.md
  - Teaching: teaching.md
